/**
 * Build one consult-gate vocabulary pack (src/core/consult-gate.ts).
 *
 * A pack is a gzip-compressed text file: a few header lines starting with "#"
 * (pack id, source, licence, regeneration command), then lower-case a-z
 * words, one per line, sorted by byte value. Its SHA-256 is printed, and must
 * be pinned in CONSULT_VOCABULARY_PACKS (shipped packs) or is recorded in the
 * local manifest (user-installed packs, scripts/install-consult-language-pack.ts).
 *
 * Every pack is normalised the same way as the gate: decompose and drop
 * accents, fold ligatures and special letters (oe, ae, o, l, d, th, ss, i),
 * lower-case, split at anything that is not a letter, keep a-z words of two or
 * more letters. Entries written with a capital letter (proper nouns) are
 * skipped, except in the medicines pack, whose brand names are its point.
 *
 * Proper nouns, two filters:
 *   - global: every pack except English and the country names drops the words
 *     on the `--exclude <file>` list, built by the `proper-nouns` command from
 *     the single-word capitalised entries of the ESDB size-80 list, minus
 *     ordinary lower-case English words of the same list (so "rose" and
 *     "mark" stay). In a hunspell pack a listed word is dropped only when the
 *     dictionary does not list it as a lower-case stem of its own, i.e. when
 *     only an affix derivation produced it ("james", "paris" go; Spanish
 *     "como" and French "le" stay; a genuine lower-case entry such as French
 *     "fenwick", a forklift, also stays);
 *   - per language: a hunspell pack drops the single-word proper nouns its own
 *     dictionary lists (capitalised stems, CAT=np or po:npr entries), so an
 *     affix expansion cannot recreate them, unless the dictionary also lists the
 *     word as a lower-case stem. Another language's proper nouns are not used:
 *     Dutch "Quelle" must not remove French "quelle".
 * Stems the dictionary marks as special (KEEPCASE, FORCEUCASE, NOSUGGEST,
 * WARN, FORBIDDENWORD, ONLYINCOMPOUND, NEEDAFFIX) are dropped, and nothing is
 * derived from a dropped stem.
 *
 * Usage:
 *   bun scripts/build-consult-vocabulary.ts proper-nouns <out-file> <esdb-80 list>
 *   bun scripts/build-consult-vocabulary.ts <pack> <out-dir> [--exclude <file>] <source...>
 * Packs and their sources:
 *   en-esdb-<size>   ESDB word list file (`./scowl word-list <size> A,B,Z,C,D 1 --deaccent --wo-poses=abbr`)
 *   nl-opentaal      unpacked npm dictionary-nl 2.0.0
 *   fr-grammalecte   unpacked npm dictionary-fr 3.0.0
 *   es-hunspell      unpacked npm dictionary-es 4.0.0
 *   pt-br-hunspell   unpacked npm dictionary-pt 4.0.0
 *   pt-pt-hunspell   unpacked npm dictionary-pt-pt 2.0.0
 *   de-hunspell      unpacked npm dictionary-de 3.0.0 (user-installed only, GPL)
 *   it-hunspell      unpacked npm dictionary-it 2.0.0 (user-installed only, GPL)
 *   olympus-terms    scripts/data/consult-olympus-terms.txt (Olympus-authored; no upstream source)
 *   places           GeoNames cities15000.txt then admin1CodesASCII.txt (CC BY 4.0)
 *   cldr-units       unpacked npm cldr-units-full 48.2.0
 *   cldr-countries   unpacked npm cldr-localenames-full 48.2.0
 *   rx-ingredients   RXNCONSO.RRF of RxNorm Current Prescribable Content (IN, PIN)
 *   rx-brands        RXNCONSO.RRF of RxNorm Current Prescribable Content (BN)
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';

const LIGATURES: Readonly<Record<string, string>> = {
  '\u0153': 'oe', '\u00E6': 'ae', '\u00F8': 'o', '\u0142': 'l', '\u0111': 'd', '\u00F0': 'd', '\u00FE': 'th', '\u00DF': 'ss', '\u0131': 'i',
};

export function vocabularyWords(text: string): string[] {
  let folded = '';
  for (const char of text.normalize('NFKD').replace(/\p{M}+/gu, '').toLowerCase()) folded += LIGATURES[char] ?? char;
  return folded.split(/[^\p{L}]+/u).filter((part) => part.length >= 2 && /^[a-z]+$/u.test(part));
}

export interface PackHeader {
  readonly id: string;
  readonly source: string;
  readonly licence: string;
}

/** Write a pack; returns its SHA-256 and word count. */
export function writePack(outDir: string, header: PackHeader, words: Set<string>): { sha256: string; words: number; bytes: number } {
  const lines = [
    `# consult-vocabulary-pack ${header.id}`,
    `# source: ${header.source}`,
    `# licence: ${header.licence}`,
    '# generated by scripts/build-consult-vocabulary.ts; do not edit by hand',
    ...[...words].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)),
  ];
  const gz = gzipSync(Buffer.from(`${lines.join('\n')}\n`, 'utf8'), { level: 9 });
  writeFileSync(join(outDir, `${header.id}.txt.gz`), gz);
  return { sha256: createHash('sha256').update(gz).digest('hex'), words: words.size, bytes: gz.length };
}

interface AffixRule {
  readonly prefix: boolean;
  readonly cross: boolean;
  readonly strip: string;
  readonly add: string;
  readonly condition: RegExp;
}

/**
 * Expand a hunspell dictionary: every stem with no capital letter (or, for
 * German, every stem: German writes all nouns capitalised, so the proper-noun
 * filter would drop the language's nouns; the cost is that the German pack also
 * admits the names its dictionary lists), plus one
 * application of each of its prefix and suffix rules, and their cross product
 * where both rules allow it. Compound rules are not applied, so compounds not
 * listed whole are absent. Stems marked forbidden or compound-only are skipped.
 */
export function expandHunspell(dir: string, keepCapitalized = false, exclude: ReadonlySet<string> = new Set()): Set<string> {
  const aff = readFileSync(join(dir, 'index.aff'), 'utf8').split('\n');
  let flagMode = 'char';
  const aliases: string[][] = [];
  const excluded = new Set<string>();
  const rules = new Map<string, AffixRule[]>();
  const splitFlags = (text: string): string[] => {
    if (!text) return [];
    if (flagMode === 'long') return text.match(/../gu) ?? [];
    if (flagMode === 'num') return text.split(',');
    return [...text];
  };
  for (const line of aff) {
    const parts = line.trim().split(/\s+/u);
    if (parts[0] === 'FLAG') flagMode = parts[1] === 'long' ? 'long' : parts[1] === 'num' ? 'num' : 'char';
  }
  for (const line of aff) {
    const parts = line.trim().split(/\s+/u);
    if (parts[0] === 'AF' && parts.length === 2 && !/^\d+$/u.test(parts[1]!)) aliases.push(splitFlags(parts[1]!));
    if (['FORBIDDENWORD', 'ONLYINCOMPOUND', 'NEEDAFFIX', 'KEEPCASE', 'FORCEUCASE', 'NOSUGGEST', 'WARN'].includes(parts[0]!) && parts[1]) excluded.add(parts[1]);
    if ((parts[0] === 'SFX' || parts[0] === 'PFX') && parts.length >= 4 && (parts[2] === 'Y' || parts[2] === 'N') && /^\d+$/u.test(parts[3]!)) {
      rules.set(`${parts[0]}:${parts[1]}:cross`, [{ prefix: false, cross: parts[2] === 'Y', strip: '', add: '', condition: /$/u }]);
      continue;
    }
    if ((parts[0] === 'SFX' || parts[0] === 'PFX') && parts.length >= 5) {
      const [kind, flag, strip, rawAdd, condition] = parts as [string, string, string, string, string];
      const prefix = kind === 'PFX';
      const cross = rules.get(`${kind}:${flag}:cross`)?.[0]?.cross ?? false;
      const add = rawAdd.split('/')[0]!;
      const pattern = condition === '.' ? '' : condition;
      let compiled: RegExp;
      try {
        compiled = new RegExp(prefix ? `^${pattern}` : `${pattern}$`, 'u');
      } catch {
        continue;
      }
      const list = rules.get(flag) ?? [];
      list.push({ prefix, cross, strip: strip === '0' ? '' : strip, add: add === '0' ? '' : add, condition: compiled });
      rules.set(flag, list);
    }
  }
  const words = new Set<string>();
  const dic = readFileSync(join(dir, 'index.dic'), 'utf8').split('\n').slice(1);
  const ownProper = new Set<string>();
  const lowerStems = new Set<string>();
  for (const entry of dic) {
    const stem = entry.split(/[/\t ]/u)[0] ?? '';
    const parts = vocabularyWords(stem);
    if (parts.length !== 1) continue;
    if (/^\p{Lu}/u.test(stem) || /CAT=np\b|po:npr\b/u.test(entry)) ownProper.add(parts[0]!);
    else lowerStems.add(parts[0]!);
  }
  for (const entry of dic) {
    const slash = entry.search(/(?<!\\)\//u);
    const stem = (slash < 0 ? entry : entry.slice(0, slash)).trim().split(/\s+/u)[0] ?? '';
    const flagText = slash < 0 ? '' : (entry.slice(slash + 1).trim().split(/\s+/u)[0] ?? '');
    if (!stem || (!keepCapitalized && /\p{Lu}/u.test(stem))) continue;
    if (/CAT=np\b|po:npr\b/u.test(entry)) continue;
    const flags = /^\d+$/u.test(flagText) && aliases.length > 0 ? (aliases[Number(flagText) - 1] ?? []) : splitFlags(flagText);
    if (flags.some((flag) => excluded.has(flag))) continue;
    const prefixed: string[] = [];
    const forms = [stem];
    const apply = (base: string, rule: AffixRule): string | undefined => {
      if (!rule.condition.test(base)) return undefined;
      if (rule.prefix) return base.startsWith(rule.strip) ? rule.add + base.slice(rule.strip.length) : undefined;
      return base.endsWith(rule.strip) ? base.slice(0, base.length - rule.strip.length) + rule.add : undefined;
    };
    for (const flag of flags) {
      for (const rule of rules.get(flag) ?? []) {
        const form = apply(stem, rule);
        if (form === undefined) continue;
        forms.push(form);
        if (rule.prefix && rule.cross) prefixed.push(form);
      }
    }
    for (const base of prefixed) {
      for (const flag of flags) {
        for (const rule of rules.get(flag) ?? []) {
          if (rule.prefix || !rule.cross) continue;
          const form = apply(base, rule);
          if (form !== undefined) forms.push(form);
        }
      }
    }
    for (const form of forms) {
      const split = vocabularyWords(form);
      if (split.length === 1) words.add(split[0]!);
    }
  }
  if (!keepCapitalized) for (const noun of ownProper) if (!lowerStems.has(noun)) words.delete(noun);
  // Global proper nouns go unless the dictionary lists the word as a lower-case
  // stem of its own ("como", "le" stay; "james", "paris" derived by an affix go).
  for (const noun of exclude) if (!lowerStems.has(noun)) words.delete(noun);
  return words;
}

/**
 * The global exclusion list: single-word capitalised entries of the ESDB
 * size-80 list, minus ordinary lower-case English words of the same list.
 */
export function properNounList(esdbList: string): Set<string> {
  const proper = new Set<string>();
  const common = new Set<string>();
  for (const line of readFileSync(esdbList, 'utf8').split('\n')) {
    if (!line) continue;
    const parts = vocabularyWords(line);
    if (/\p{Lu}/u.test(line)) {
      if (parts.length === 1 && !/[\s-]/u.test(line)) proper.add(parts[0]!);
    } else {
      for (const word of parts) common.add(word);
    }
  }
  for (const word of common) proper.delete(word);
  return proper;
}

function excluding(words: Set<string>, exclude: ReadonlySet<string>): Set<string> {
  for (const word of exclude) words.delete(word);
  return words;
}

function packageVersion(dir: string): string {
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as { name: string; version: string };
  return `${pkg.name} ${pkg.version}`;
}

const HUNSPELL_PACKS: Readonly<Record<string, string>> = {
  'nl-opentaal': 'BSD-3-Clause (chosen from BSD-3-Clause OR CC-BY-3.0)',
  'fr-grammalecte': 'MPL-2.0',
  'es-hunspell': 'MPL-1.1 (chosen from GPL-3.0+ OR LGPL-3.0+ OR MPL-1.1+)',
  'pt-br-hunspell': 'MPL-2.0 (chosen from LGPL-3.0 OR MPL-2.0)',
  'pt-pt-hunspell': 'MPL-1.1 (chosen from GPL-2.0 OR LGPL-2.1 OR MPL-1.1)',
  'de-hunspell': 'GPL-2.0 OR GPL-3.0 (user-installed; never shipped)',
  'it-hunspell': 'GPL-3.0 (user-installed; never shipped)',
};

export function buildPack(
  pack: string,
  outDir: string,
  sources: readonly string[],
  exclude: ReadonlySet<string> = new Set(),
): { sha256: string; words: number; bytes: number } {
  const esdb = /^en-esdb-(\d+)$/u.exec(pack);
  if (esdb) {
    const words = new Set<string>();
    for (const line of readFileSync(sources[0]!, 'utf8').split('\n')) {
      if (!line || /\p{Lu}/u.test(line)) continue;
      for (const word of vocabularyWords(line)) words.add(word);
    }
    return writePack(outDir, {
      id: 'en-esdb',
      source: `English Speller Database (SCOWL) rel-2026.02.25, size ${esdb[1]}, all spellings, variant level 1, no abbreviations, no capitalised entries`,
      licence: 'SCOWL/ESDB copyright notice (permissive); see en-esdb.LICENSE.txt',
    }, words);
  }
  const licence = HUNSPELL_PACKS[pack];
  if (licence) {
    return writePack(outDir, {
      id: pack,
      source: `npm ${packageVersion(sources[0]!)}, expanded with its own affix rules (one level, no compounds) by scripts/build-consult-vocabulary.ts`,
      licence: licence.startsWith('MPL') ? `${licence}. This file is Covered Software under the MPL; its source form is the upstream package named above plus scripts/build-consult-vocabulary.ts.` : licence,
    }, expandHunspell(sources[0]!, pack === 'de-hunspell', exclude));
  }
  if (pack === 'places') {
    // cities15000.txt (tab-separated; columns 1 and 2 are name and asciiname) and
    // admin1CodesASCII.txt (code, name, asciiname, id). Alternate names are not used.
    const words = new Set<string>();
    for (const [file, minColumns] of [[sources[0]!, 3], [sources[1]!, 3]] as const) {
      for (const line of readFileSync(file, 'utf8').split('\n')) {
        const fields = line.split('\t');
        if (fields.length < minColumns) continue;
        for (const name of [fields[1]!, fields[2]!]) for (const word of vocabularyWords(name)) words.add(word);
      }
    }
    return writePack(outDir, {
      id: pack,
      source: 'GeoNames (https://www.geonames.org/) cities15000.txt (populated places of 15,000 or more) and admin1CodesASCII.txt (first-level regions), downloaded 2026-10-07 from https://download.geonames.org/export/dump/; name and asciiname columns only',
      licence: 'CC BY 4.0 (attribution: GeoNames); see places.LICENSE.txt',
    }, words);
  }
  if (pack === 'olympus-terms') {
    const words = new Set<string>();
    for (const line of readFileSync(sources[0]!, 'utf8').split('\n')) {
      if (!line.trim() || line.startsWith('#')) continue;
      for (const word of vocabularyWords(line)) words.add(word);
    }
    return writePack(outDir, {
      id: pack,
      source: 'Olympus-authored list of general terms (units, file formats, protocols, device and network terms, a few stable general proper terms): scripts/data/consult-olympus-terms.txt',
      licence: `Olympus-authored, no third-party data; see ${pack}.LICENSE.txt`,
    }, words);
  }
  if (pack === 'cldr-units' || pack === 'cldr-countries') {
    const dir = sources[0]!;
    const words = new Set<string>();
    for (const locale of ['en', 'es', 'fr', 'de', 'it', 'pt', 'nl']) {
      if (pack === 'cldr-countries') {
        const territories = (JSON.parse(readFileSync(join(dir, 'main', locale, 'territories.json'), 'utf8')) as {
          main: Record<string, { localeDisplayNames: { territories: Record<string, string> } }>;
        }).main[locale]!.localeDisplayNames.territories;
        for (const [code, name] of Object.entries(territories)) {
          if (/^(?:[A-Z]{2}|\d{3})(?:-alt-[a-z]+)?$/u.test(code)) for (const word of vocabularyWords(name)) words.add(word);
        }
      } else {
        const units = (JSON.parse(readFileSync(join(dir, 'main', locale, 'units.json'), 'utf8')) as {
          main: Record<string, { units: Record<string, unknown> }>;
        }).main[locale]!.units;
        const visit = (value: unknown): void => {
          if (typeof value === 'string') for (const word of vocabularyWords(value.replace(/\{\d\}/gu, ' '))) words.add(word);
          else if (value && typeof value === 'object') for (const child of Object.values(value)) visit(child);
        };
        visit(units);
      }
    }
    return writePack(outDir, {
      id: pack,
      source: `Unicode CLDR 48.2 (${packageVersion(dir)}): ${pack === 'cldr-units' ? 'unit names and patterns' : 'country and macro-region names'} in en es fr de it pt nl`,
      licence: `Unicode-3.0; see ${pack}.LICENSE.txt`,
    }, pack === 'cldr-units' ? excluding(words, exclude) : words);
  }
  if (pack === 'rx-ingredients' || pack === 'rx-brands') {
    // RXNCONSO columns: RXCUI|LAT|TS|LUI|STT|SUI|ISPREF|RXAUI|SAUI|SCUI|SDUI|SAB|TTY|CODE|STR|...
    // Only names that are one word: multi-word strings (combinations, strain
    // designations, dose forms) are never split into independent words, and
    // anything with a digit, slash, bracket or the words strain/virus/vaccine
    // is skipped outright.
    const keep = new Set(pack === 'rx-ingredients' ? ['IN', 'PIN'] : ['BN']);
    const words = new Set<string>();
    for (const line of readFileSync(sources[0]!, 'utf8').split('\n')) {
      const fields = line.split('|');
      if (fields[11] !== 'RXNORM' || !keep.has(fields[12] ?? '')) continue;
      const name = fields[14] ?? '';
      if (/[\d/()[\]]|strain|virus|vaccine/iu.test(name)) continue;
      const parts = vocabularyWords(name);
      if (parts.length === 1 && name.trim().split(/\s+/u).length === 1) words.add(parts[0]!);
    }
    return writePack(outDir, {
      id: pack,
      source: `NLM RxNorm Current Prescribable Content, release 2026-10-05 (RxNorm_full_prescribe_10052026.zip): single-word RXNORM ${pack === 'rx-ingredients' ? 'IN and PIN (ingredient)' : 'BN (brand)'} names`,
      licence: `Public domain (no licence required); NLM attribution in ${pack}.LICENSE.txt`,
    }, excluding(words, exclude));
  }
  throw new Error(`unknown pack ${pack}`);
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args[0] === 'proper-nouns') {
    const [, outFile, esdbList] = args;
    if (!outFile || !esdbList) throw new Error('usage: proper-nouns <out-file> <esdb-80 list>');
    const nouns = properNounList(esdbList);
    writeFileSync(outFile, `${[...nouns].sort().join('\n')}\n`);
    console.log(`proper-nouns\t${nouns.size} words`);
  } else {
    const [pack, outDir, ...rest] = args;
    let exclude = new Set<string>();
    if (rest[0] === '--exclude') {
      exclude = new Set(readFileSync(rest[1]!, 'utf8').split('\n').filter(Boolean));
      rest.splice(0, 2);
    }
    if (!pack || !outDir || rest.length === 0) throw new Error('usage: bun scripts/build-consult-vocabulary.ts <pack> <out-dir> [--exclude <file>] <source...>');
    const result = buildPack(pack, outDir, rest, exclude);
    console.log(`${pack}\t${result.words} words\t${result.bytes} bytes gz\tsha256 ${result.sha256}`);
  }
}
