export {
  ConnectorStoreExclusionViolationError,
  ConnectorStoreLocatorIdentityIndexNotReadyError,
  ConnectorStoreMetadataOnlyViolationError,
  LocalConnectorStore,
  // The store's own chunking recipe, namespaced for outside callers. Anything
  // that has to predict what the store will write about a piece of text runs
  // these rather than keeping a copy in step by hand.
  chunkText as connectorStoreChunkText,
  hashString as connectorStoreHashString,
  DEFAULT_MAX_CHUNK_CHARS as CONNECTOR_STORE_DEFAULT_MAX_CHUNK_CHARS,
  createConnectorStoreContentProvider,
  createConnectorStoreCorpusAdapter,
  connectorStoreCoverageGaps,
  connectorStoreCurrentEmbeddingModelId,
  connectorStoreCurrentEmbeddingRows,
  connectorStoreCurrentEmbeddingRowsIterator,
  connectorStoreQualificationFingerprint,
  DEFAULT_SEMANTIC_RELEVANCE_BAR,
  normalizeConnectorStoreSearchFilters,
  repairConnectorStoreSendersFromConnector,
  syncAndEmbedFromConnector,
  verifyConnectorStoreCorpusIntegrity,
  defineConnectorCorpus,
  type ConnectorCorpusOptions,
  type ConnectorStoreClassificationOptions,
  type ConnectorStoreAbsenceAuthority,
  type ConnectorStoreCurrentMembershipAuthority,
  type ConnectorStoreCoverageGap,
  type ConnectorStoreContentProviderOptions,
  type ConnectorStoreCorpusAdapterOptions,
  type ConnectorStoreExclusionCounts,
  type ConnectorStorePurgeSummary,
  type ConnectorStoreMetadataOnlyStripSummary,
  type ConnectorStoreEmbedOptions,
  type ConnectorStoreEmbedSummary,
  type ConnectorStoreLocalContent,
  type ConnectorStoreActiveLocatorItem,
  type ConnectorStoreItemPresence,
  type ConnectorStoreItemMetadataSnapshot,
  type ConnectorStoreLocatorIdentityBackfillSummary,
  type ConnectorStoreLocatorIdentityIndexStatus,
  type ConnectorStoreExtractionCandidate,
  type ConnectorStoreExtractionCandidateOptions,
  type ConnectorStoreExtractionCandidatePage,
  type ConnectorStoreCurrentItemRepresentationCoverage,
  type ConnectorStoreCorpusIntegrityOptions,
  type ConnectorStoreCorpusIntegrityReport,
  type ConnectorStoreCurrentEmbeddingRow,
  type ConnectorStoreItemRepresentationCoverage,
  type ConnectorStoreActiveIdentityPage,
  type ConnectorStoreRelinquishOptions,
  type ConnectorStoreRelinquishSummary,
  type ConnectorStoreTrustReconciliationOptions,
  type ConnectorStoreTrustReconciliationStatus,
  type ConnectorStoreTrustReconciliationSummary,
  type ConnectorStoreRepresentationRestoreItem,
  type ConnectorStoreRepresentationRestoreOptions,
  type ConnectorStoreRepresentationRestoreSummary,
  type ConnectorStoreQualificationFingerprint,
  type ConnectorStoreItemRepresentationExpectation,
  type ConnectorStoreOwnershipKind,
  type ConnectorStoreSearchRow,
  type ConnectorStoreScoredSearchRow,
  type ConnectorStoreSearchFilters,
  type ConnectorStoreSenderAggregation,
  type ConnectorStoreSenderAggregationOptions,
  type ConnectorStoreSenderMetadata,
  type ConnectorStoreSenderRepairOptions,
  type ConnectorStoreSenderRepairRecord,
  type ConnectorStoreSenderRepairSummary,
  type ConnectorStoreConnectorSenderRepairSummary,
  type ConnectorStoreSearchTextRepairOptions,
  type ConnectorStoreSearchTextRepairSummary,
  type ConnectorStoreOwnedSearchFacetRefreshRecord,
  type ConnectorStoreOwnedSearchFacetRefreshSummary,
  type ConnectorStoreStatus,
  type ConnectorStoreSyncOptions,
  type ConnectorStoreSyncRun,
  type ConnectorStoreSyncSummary,
  type ConnectorStoreSyncAndEmbedOptions,
  type ConnectorStoreSyncAndEmbedSummary,
  type LocalConnectorStoreOptions,
} from './local-index.ts';

export {
  CONNECTOR_STORE_DECLARED_FILTER_FIELDS,
  connectorStoreFilterCapabilityRegistry,
  undeclaredConnectorStoreSearchRequestFields,
  unsupportedConnectorStoreFilterFields,
  type ConnectorStoreDeclaredFilterField,
  type ConnectorStoreFamilyFilterCapabilities,
  type ConnectorStoreFilterCapabilityIdentity,
  type ConnectorStoreFilterCapabilityRegistry,
  type ConnectorStoreFilterCapabilityScope,
  type ConnectorStoreChatScopeFilterCodec,
  type ConnectorStoreChatScopeResolution,
  type ConnectorStoreApprovedScopeFilterCodec,
  type ConnectorStoreApprovedScopeResolution,
  type ConnectorStoreConversationTitleCandidate,
  type ConnectorStoreConversationTitleCandidates,
  type ConnectorStoreFolderFilterCodec,
  type ConnectorStoreResultProjectionInput,
  type ConnectorStoreResultProjector,
  type ConnectorStoreResultProjectorCodec,
} from './filter-capabilities.ts';
